services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Packages\Event\Processor\EventProcessorInterface:
            tags: [ 'app.event_processor' ]

    Packages\Event\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
