name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    -   title: '🚀 Features'
        collapse-after: 5
        labels:
            - 'feature'
    -   title: '🐛 Bug Fixes'
        collapse-after: 5
        labels:
            - 'bug'
    -   title: '🧰 Maintenance'
        collapse-after: 5
        label: 'chore'
autolabeler:
    -   label: 'chore'
        branch:
            - '/chore\/.+/'
    -   label: 'bug'
        branch:
            - '/bug\/.+/'
    -   label: 'feature'
        branch:
            - '/feature\/.+/'
version-resolver:
    major:
        labels:
            - 'bump-major'
    minor:
        labels:
            - 'bump-minor'
    patch:
        labels:
            - 'bump-patch'
    default: patch
exclude-labels:
    - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
    ## What's Changed

    $CHANGES