services:
    _defaults:
        autowire: true
        autoconfigure: true

    Packages\Telemetry\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    Symfony\Component\Clock\NativeClock: ~

    Packages\Telemetry\Service\MetricServiceInterface:
        class: Packages\Telemetry\Service\MetricService

    telemetry.symfony_serializer_line_formatter:
        class: Packages\Telemetry\Service\SymfonySerializerLineFormatter

    telemetry.metrics_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: [ "%%message%%\n" ]