services:
    _defaults:
        autowire: true
        autoconfigure: true

    Packages\Telemetry\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    Symfony\Component\Clock\NativeClock: ~

    Packages\Telemetry\Service\MetricServiceInterface:
        class: Packages\Telemetry\Service\MetricService