framework:
    secret: '%env(APP_SECRET)%'

    router:
        utf8: true

when@test:
    framework:
        test: true

when@prod:
    framework:
        router:
            strict_requirements: null
