when@dev: &aws_dev
    async_aws:
        clients:
            event-bridge:
                config:
                    endpoint: 'http://localstack:4587'
            scheduler:
                config:
                    endpoint: 'http://localstack:4587'

when@test: *aws_dev