# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true

    php_errors:
        log: true

when@test:
    framework:
        test: true
