<?php

namespace Packages\Contracts\PublishableMessage;

enum PublishableMessage: string
{
    case PULL_REQUEST = 'PULL_REQUEST';
    case CHECK_RUN = 'CHECK_RUN';
    case MISSING_COVERAGE_LINE_COMMENT = 'MISSING_COVERAGE_LINE_COMMENT';
    case PARTIAL_BRANCH_LINE_COMMENT = 'PARTIAL_BRANCH_LINE_COMMENT';
    case COLLECTION = 'COLLECTION';
    case LINE_COMMENT_COLLECTION = 'LINE_COMMENT_COLLECTION';
}
