monolog:
    handlers:
        metrics:
            type: stream
            path: "php://stdout"
            formatter: telemetry.metrics_formatter
            level: info
            channels: [ 'metrics' ]

    channels: [ 'metrics' ]