services:
    _defaults:
        autowire: true
        autoconfigure: true

    Packages\Local\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    Packages\Local\Command\InvokeEventCommand:
        tags:
            - { name: 'console.command', command: 'event:invoke' }