version: "3.9"

services:
    lambda:
        image: bref/php-84-fpm-dev:2
        volumes:
            - .:/var/task:ro
            - ./var:/var/task/var
            - ../../packages:/var/task/vendor/coverage-robot