services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Handler\EventHandler:
        # The handler must be public so that Bref is able to run it through the Symfony
        # runtime
        public: true

    Psr\Container\ContainerInterface: '@service_container'

    Packages\Contracts\Environment\EnvironmentServiceInterface: '@App\Service\EnvironmentService'

    # Metric publishing
    Symfony\Component\Clock\NativeClock: ~

    Psr\Clock\ClockInterface: '@Symfony\Component\Clock\NativeClock'

    Packages\Telemetry\Service\MetricService: ~

    # Message publishing
    Packages\Clients\Client\Github\GithubAppClient:
        arguments:
            $appId: '%env(GITHUB_APP_ID)%'
            $privateKeyFile: './config/github.pem'

    Packages\Clients\Client\Github\GithubAppInstallationClient: ~

    Packages\Clients\Generator\JwtGenerator: ~