services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Handler\EventHandler:
        # The handler must be public so that Bref is able to run it through the Symfony
        # runtime
        public: true

    App\Extension\CoverageTemplateSecurityPolicy:
        arguments:
            $allowedTags: [
                'apply',
                'autoescape',
                'for',
                'if',
                'set',
                'verbatim',
                'with',
            ]
            $allowedFilters: [
                'abs',
                'batch',
                'capitalize',
                'column',
                'convert_encoding',
                'country_name',
                'currency_name',
                'currency_symbol',
                'data_uri',
                'date',
                'date_modify',
                'default',
                'escape',
                'filter',
                'first',
                'format',
                'format_currency',
                'format_date',
                'format_datetime',
                'format_number',
                'format_time',
                'html_to_markdown',
                'join',
                'json_encode',
                'keys',
                'language_name',
                'last',
                'length',
                'locale_name',
                'lower',
                'map',
                'merge',
                'nl2br',
                'number_format',
                'raw',
                'reduce',
                'replace',
                'reverse',
                'round',
                'slice',
                'slug',
                'sort',
                'spaceless',
                'split',
                'striptags',
                'timezone_name',
                'title',
                'trim',
                'u',
                'upper',
                'url_encode',
            ]
            $allowedFunctions: [
                'attribute',
                'cycle',
                'date',
                'html_classes',
                'include',
                'max',
                'min',
                'random',
                'range',
                'country_timezones',
                'country_names',
                'currency_names',
                'language_names',
                'locale_names',
                'script_names',
                'timezone_names'
            ]
            $allowedMethods: []
            $allowedProperties: []